### ISSUE TITLE
pycparser missing requirement?

### ISSUE THREAD

**Issue by catichenor** [joshlk/many_requests#3]
Hi, thanks for writing this, this was a pretty simple replacement for some "requests" code in a reporting script I created at work. 

One issue I ran into when using this on a [poetry](https://github.com/python-poetry/poetry) setup was that after using `poetry add many-requests`, I got an error that `pycparser` was needed to be able to run many-requests (I didn't get this error on my local machine, which had a conda installation + several other libraries previously installed). After running `poetry add pycparser`, many-requests worked without a hitch.

Perhaps this can be added to the requirements?

**Comment by joshlk** [comment]
Hi @catichenor, glad that the project has been of help 😃.

I can't reproduce this issue. This is what I tried in the shell, I'm using a docker image to obtain a fresh Python installation but you can omit the first line if thats not required:

```bash
docker run -it python:3.7.9 bash
pip install poetry
poetry new test
cd test
poetry add many-requests
poetry run python -c "import many_requests"
```

It might be another package that is requiring `pycparser`? Or can you please provide a minimal working example which demonstrates the error - thanks.

Josh

**Comment by joshlk** [comment]
Please reopen the issue if your still having problems
