### ISSUE TITLE
Headers Error

### ISSUE THREAD

**Issue by williambarberjr** [joshlk/many_requests#4]
I'm getting an error I can't seem to resolve related to the header argument when I pass it a dict.

I'm on mobile at the moment, will post a representative example of the error later tonight. But may be able to resolve the issue myself if you can provide a working example with a header argument.

**Comment by williambarberjr** [comment]
I think I've established that the json argument isn't being processed correctly. I'm passing a dictionary within a dictionary as the json argument, and, in the below example, only 'Remove' is sent.

```
postPayload = {'Remove': {'Missing': 'NotSent'}}

#this doesn't work 
responses = ManyRequests(n_workers=5, n_connections=5)(
            method='POST',
            url=allUrls[5:15],
            json = postPayload,
            cookies = [custom_cookies]*10)

#WARNING:root:FAILED Request {'method': 'POST', 'url': ...
#'json': 'Remove', ...
#Permanently failed. Last error: Bad response status code: 400. Should be in (200,)
```

**Comment by williambarberjr** [comment]
Solved this. If you send the json input as a list, this issue doesn't occur. Like the below.

`
responses = ManyRequests(n_workers=5, n_connections=5)(
                method='POST',
                url=allUrls[5:15],
                json = [postPayload]*10,
                cookies = [custom_cookies]*10)
`

**Comment by joshlk** [comment]
Yes - glad you sorted it. I think it's getting confused as the dictionary is technically an iterable - this is how it determines whether it should duplicate the item or not: https://github.com/joshlk/many_requests/blob/main/many_requests/easy_async.py#L39
