### ISSUE TITLE
SSLError Stops Processing

### ISSUE THREAD

**Issue by williambarberjr** [joshlk/many_requests#6]
I have a script that pulls html for a list of domains. I don't know the full web addresses, just the domains, in this case, alfalaval.us, the script passes "https://alfalaval.us" to ManyRequests along with the others, and when that attempt runs, it throws an SSL connection error, and all processing stops. All that needs to be done to avoid the error in this case is pinging "https://www.alfalaval.us" instead. 
Really two issues here:
1. I would prefer that I got an error message in the output after all requests were processed rather than processing stopping and an error being thrown.
2. Even when I catch this error, I have to parse it a bit to drop the problematic url from the requests list:
```
responses = []
    while responses == []:
        try:
            responses = ManyRequests(n_workers=2, n_connections=2, retries = 0)(
                    method='GET',
                    url=urls)
        except Exception as e:
            print(e)
            if str(type(e)) == "<class 'ssl.SSLCertVerificationError'>":
                thisUrl = re.findall("not valid for '(.*?)'", str(e))[0]
                urlstring = 'https://' + thisUrl
                print("dropping: " + urlstring)
                if urlstring in urls:
                    urls.pop(urls.index(urlstring))
```

Is there a better way to handle these errors?

**Comment by joshlk** [comment]
Hi @williambarberjr, I have update `many-requests` so that SSL errors are caught in the usual way i.e. a `BadResponse` will be included in the corresponding position of the output list.

For future reference:

Previously this raised a `ssl.SSLCertVerificationError`:
```
from many_requests import ManyRequests
urls = ['https://alfalaval.us']
responses = ManyRequests(n_workers=2, n_connections=2, retries = 0)(
                     method='GET',
                     url=urls)
```

While now (since v0.2.1) it will run correctly and `responses` will include a `BadResponse` object.

**Comment by joshlk** [comment]
Please feel free to contact me again if you have any other issues 😃

**Comment by williambarberjr** [comment]
Will do, thanks for fixing this!
