### ISSUE TITLE
Question about memory usage

### ISSUE THREAD

**Issue by karkraeg** [joshlk/many_requests#7]
Hi! Sorry if this is a dumb question - but is there a way to access the responses while requests are still running? If I would want to download a huge number of XML records in parallel (say > 1 million, each return object around 500kb) I would most certainly run into some sort of memory shortage, wouldn’t ? 

My basic usage is like this:

```
# urls = list containing a lot of URLs

responses = ManyRequests(n_workers=16, n_connections=128)(
                method='GET',
                url=[i for i in urls])

for r in responses:
    # save r.text to file
```

This works fine for 4000 URLs (consuming about 150mb RAM max) but as I said I would be interested in a way to kind of use this like a generator.

Thanks for helping me out!

**Comment by joshlk** [comment]
Hi, thanks for your interest in the package!

Unfortunately the way the library is structured this is not possible or easily possible with a small code modifications. You would need to change the way it interacts with trio here and make it a generator:

https://github.com/joshlk/many_requests/blob/f80df66c8b5cd0f59b3ef31622a36e8ebd30094e/many_requests/easy_async.py#L104

**Comment by karkraeg** [comment]
Hi, thanks for your answer! I guess I’ll look into aiohttp before tinkering with packages I’ve never heard of. So thanks and thank you for your package!
